const events = [
  {
    id: "prompt-2-product",
    name: "Prompt 2 Product",
    date: "8 October 2026",
    time: "10:00 AM – 4:00 PM",
    venue: "AITR, Indore",
    category: "AI & Technology",
    theme: "AI & Prompt Engineering",
    description: "Turn an idea into a working prototype using AI and thoughtful prompts.",
    details: "Explore prompt engineering, prototype quickly, and present your solution to fellow students.",
    organizer: "CSI AITR Student Chapter",
  },
  {
    id: "web-development",
    name: "Web Development Workshop",
    date: "15 October 2026",
    time: "11:00 AM – 2:00 PM",
    venue: "Computer Lab 2, AITR",
    category: "Web Development",
    theme: "HTML & CSS",
    description: "Build and style your first responsive web page with HTML and CSS.",
    details: "Learn the foundations of modern websites through practical exercises and leave with a page you built yourself.",
    organizer: "CSI AITR Student Chapter",
  },
  {
    id: "git-github",
    name: "Git and GitHub Workshop",
    date: "22 October 2026",
    time: "1:00 PM – 3:30 PM",
    venue: "Seminar Hall, AITR",
    category: "Workshop",
    theme: "Developer Tools",
    description: "Get comfortable with version control and collaborating on code.",
    details: "Practice commits, branches, pull requests, and the workflow used by real development teams.",
    organizer: "CSI AITR Student Chapter",
  },
  {
    id: "coding-challenge",
    name: "Coding Challenge",
    date: "29 October 2026",
    time: "10:30 AM – 1:00 PM",
    venue: "Innovation Lab, AITR",
    category: "Programming",
    theme: "Problem Solving",
    description: "Test your problem-solving skills in a friendly coding contest.",
    details: "Solve programming problems of varying difficulty, learn new approaches, and compete with your peers.",
    organizer: "CSI AITR Student Chapter",
  },
  {
    id: "ai-tools",
    name: "AI Tools Workshop",
    date: "5 November 2026",
    time: "11:00 AM – 1:30 PM",
    venue: "Smart Classroom, AITR",
    category: "AI & Technology",
    theme: "Practical AI",
    description: "Explore useful AI tools for studying, creating, and building.",
    details: "Try everyday AI tools in guided activities and discuss responsible ways to use them in student projects.",
    organizer: "CSI AITR Student Chapter",
  },
  {
    id: "csi-hackathon",
    name: "CSI Hackathon",
    date: "12 November 2026",
    time: "9:00 AM – 5:00 PM",
    venue: "AITR Campus, Indore",
    category: "Hackathon",
    theme: "Innovation",
    description: "Team up and create practical solutions to real-world problems.",
    details: "An all-day build sprint where teams brainstorm, prototype, and pitch a solution to a real challenge.",
    organizer: "CSI AITR Student Chapter",
  },
  {
    id: "ui-ux-design",
    name: "UI/UX Design Session",
    date: "19 November 2026",
    time: "12:00 PM – 2:00 PM",
    venue: "Design Studio, AITR",
    category: "Design",
    theme: "Design Thinking",
    description: "Learn to shape intuitive digital experiences through design.",
    details: "From sketches to screens, discover how to research user needs and design clearer interfaces.",
    organizer: "CSI AITR Student Chapter",
  },
  {
    id: "tech-talk",
    name: "Tech Talk",
    date: "26 November 2026",
    time: "2:00 PM – 4:00 PM",
    venue: "Auditorium, AITR",
    category: "Technology",
    theme: "Technology & Careers",
    description: "Hear fresh perspectives on technology and careers from the community.",
    details: "Join an open conversation about technology trends, student projects, and finding your path in tech.",
    organizer: "CSI AITR Student Chapter",
  },
];

export default events;
