// CSI Event Companion: a small, local-only demo. Nothing is sent to a server.
const events = [
  {id:'prompt-2-product',name:'Prompt 2 Product',date:'2026-10-08',time:'10:00 AM – 4:00 PM',venue:'AITR, Indore',category:'AI & Technology',description:'Turn an idea into a working prototype using AI and thoughtful prompts.',details:'Build something useful from a simple idea. Explore prompt engineering, prototype quickly, and present your solution to fellow students.',organizer:'CSI AITR Student Chapter',seats:60,fee:'₹100 per team',team:'1–2 members',theme:'AI & Prompt Engineering',tone:'blue',symbol:'✦',rules:['Teams can have 1–2 members.','Bring your own laptop and college ID.','Original ideas and respectful collaboration are encouraged.'],schedule:[['10:00 AM','Registration'],['10:30 AM','Introduction'],['11:00 AM','Workshop'],['01:00 PM','Break'],['02:00 PM','Competition'],['04:00 PM','Results']]},
  {id:'web-development',name:'Web Development Workshop',date:'2026-10-15',time:'11:00 AM – 2:00 PM',venue:'Computer Lab 2, AITR',category:'Web Development',description:'Build and style your first responsive web page with HTML and CSS.',details:'Learn the foundations of modern websites through practical exercises and leave with a page you built yourself.',organizer:'CSI AITR Student Chapter',seats:45,fee:'Free',team:'Individual',theme:'HTML & CSS',tone:'purple',symbol:'⌘',rules:['Bring your own laptop if available.','Basic computer knowledge is enough.'],schedule:[['11:00 AM','Welcome and setup'],['11:30 AM','HTML and CSS basics'],['12:30 PM','Build session'],['01:45 PM','Showcase']]},
  {id:'git-github',name:'Git and GitHub Workshop',date:'2026-10-22',time:'1:00 PM – 3:30 PM',venue:'Seminar Hall, AITR',category:'Workshop',description:'Get comfortable with version control and collaborating on code.',details:'Practice commits, branches, pull requests, and the workflow used by real development teams.',organizer:'CSI AITR Student Chapter',seats:55,fee:'Free',team:'Individual',theme:'Developer Tools',tone:'teal',symbol:'⌥',rules:['Bring your laptop.','Create a free GitHub account before the session.'],schedule:[['01:00 PM','Introduction'],['01:30 PM','Hands-on Git'],['02:30 PM','GitHub collaboration']]},
  {id:'coding-challenge',name:'Coding Challenge',date:'2026-10-29',time:'10:30 AM – 1:00 PM',venue:'Innovation Lab, AITR',category:'Programming',description:'Test your problem-solving skills in a friendly coding contest.',details:'Solve programming problems of varying difficulty, learn new approaches, and compete with your peers.',organizer:'CSI AITR Student Chapter',seats:80,fee:'Free',team:'Individual',theme:'Problem Solving',tone:'indigo',symbol:'{ }',rules:['Use your own laptop.','Individual participation only.','Any programming language is welcome.'],schedule:[['10:30 AM','Check-in'],['11:00 AM','Challenge begins'],['12:30 PM','Submissions close'],['01:00 PM','Results']]},
  {id:'ai-tools',name:'AI Tools Workshop',date:'2026-11-05',time:'11:00 AM – 1:30 PM',venue:'Smart Classroom, AITR',category:'AI & Technology',description:'Explore useful AI tools for studying, creating, and building.',details:'Try everyday AI tools in guided activities and discuss responsible ways to use them in student projects.',organizer:'CSI AITR Student Chapter',seats:50,fee:'Free',team:'Individual',theme:'Practical AI',tone:'coral',symbol:'✳',rules:['Bring your laptop or tablet.','Use AI tools responsibly.'],schedule:[['11:00 AM','Introduction'],['11:30 AM','Tool demonstrations'],['12:30 PM','Hands-on practice']]},
  {id:'csi-hackathon',name:'CSI Hackathon',date:'2026-11-12',time:'9:00 AM – 5:00 PM',venue:'AITR Campus, Indore',category:'Hackathon',description:'Team up and create practical solutions to real-world problems.',details:'An all-day build sprint where teams brainstorm, prototype, and pitch a solution to a real challenge.',organizer:'CSI AITR Student Chapter',seats:120,fee:'Free',team:'2–4 members',theme:'Innovation',tone:'blue',symbol:'⚡',rules:['Teams can have 2–4 members.','Bring your own laptops.','All work must be created during the event.'],schedule:[['09:00 AM','Registration'],['09:30 AM','Problem statements'],['10:00 AM','Building begins'],['01:00 PM','Lunch break'],['04:00 PM','Presentations'],['05:00 PM','Results']]},
  {id:'ui-ux',name:'UI/UX Design Session',date:'2026-11-19',time:'12:00 PM – 2:00 PM',venue:'Design Studio, AITR',category:'Other',description:'Learn to shape intuitive digital experiences through design.',details:'From sketches to screens, discover how to research user needs and design clearer interfaces.',organizer:'CSI AITR Student Chapter',seats:40,fee:'Free',team:'Individual',theme:'Design Thinking',tone:'purple',symbol:'◈',rules:['No design experience needed.','Bring a notebook or laptop.'],schedule:[['12:00 PM','Design thinking'],['12:45 PM','Sketching activity'],['01:30 PM','Feedback and discussion']]},
  {id:'tech-talk',name:'Tech Talk',date:'2026-11-26',time:'2:00 PM – 4:00 PM',venue:'Auditorium, AITR',category:'Other',description:'Hear fresh perspectives on technology and careers from the community.',details:'Join an open conversation about technology trends, student projects, and finding your path in tech.',organizer:'CSI AITR Student Chapter',seats:150,fee:'Free',team:'Individual',theme:'Technology & Careers',tone:'green',symbol:'✧',rules:['Arrive 15 minutes early.','Questions are welcome during the discussion.'],schedule:[['02:00 PM','Welcome'],['02:15 PM','Guest talk'],['03:15 PM','Q&A'],['03:45 PM','Networking']]}
];
const navItems=[['home','Home','⌂'],['events','Events','▦'],['saved','Saved','♡'],['registrations','Registrations','▤'],['profile','Profile','♙']];
const app=document.querySelector('#app');
const dialog=document.querySelector('#register-dialog');
const form=document.querySelector('#register-form');
const toast=document.querySelector('#toast');
const defaults={name:'Student Name',email:'student@aitr.ac.in',college:'Acropolis Institute of Technology & Research',branch:'Computer Science'};
const load=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem('csi-'+key));return value??fallback}catch{return fallback}};
let registrations=load('registrations',{}), saved=load('saved',[]), profile=load('profile',defaults);
if(!registrations || Array.isArray(registrations) || typeof registrations!=='object')registrations={};
if(!Array.isArray(saved))saved=[];
if(!profile || typeof profile!=='object')profile={...defaults};
let activeEvent=null,previousPage='events',search='',category='',status='',editing=false,toastTimer;
const store=(key,value)=>localStorage.setItem('csi-'+key,JSON.stringify(value));
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const eventDate=e=>new Date(e.date+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'});
const shortDate=e=>new Date(e.date+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});
const isPast=e=>e.date<new Date().toLocaleDateString('en-CA');
const iconSaved=e=>saved.includes(e.id)?'♥':'♡';
function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3200)}
function nav(){const current=location.hash.slice(1).split('/')[0]||'home';const link=([id,label,icon],mobile)=>`<a href="#${id}" class="nav-link ${current===id?'active':''}" ${current===id?'aria-current="page"':''}>${mobile?`<span class="nav-icon" aria-hidden="true">${icon}</span>`:''}<span>${label}</span></a>`;document.querySelector('#desktop-nav').innerHTML=navItems.map(item=>link(item,false)).join('');document.querySelector('#mobile-nav').innerHTML=navItems.map(item=>link(item,true)).join('');document.querySelector('.avatar').textContent=(profile.name||'S').trim().charAt(0).toUpperCase()||'S'}
function card(e){return `<article class="event-card"><div class="card-art" data-tone="${e.tone}"><span class="mini-brand">CSI AITR · 2026</span><span class="art-symbol" aria-hidden="true">${e.symbol}</span><strong class="art-title">${e.name}</strong></div><div class="card-body"><div class="card-top"><span class="category-pill">${e.category}</span><button class="save-button ${saved.includes(e.id)?'saved':''}" data-save="${e.id}" type="button" aria-label="${saved.includes(e.id)?'Remove saved event':'Save event'}: ${e.name}" title="${saved.includes(e.id)?'Remove saved event':'Save event'}">${iconSaved(e)}</button></div><h3>${e.name}</h3><p class="card-description">${e.description}</p><div class="meta-row"><span>⌖ ${e.venue}</span></div><div class="card-bottom"><span class="date-tag">▦ ${shortDate(e)}</span><a class="button button-outline" href="#event/${e.id}">View Details →</a></div></div></article>`}
function empty(symbol,title,description,link,label){return `<div class="empty-state"><span class="empty-icon">${symbol}</span><h3>${title}</h3><p>${description}</p>${link?`<a class="button button-primary" href="#${link}">${label} →</a>`:''}</div>`}
function home(){const featured=events[0];app.innerHTML=`<section class="hero-band"><div class="hero-inner"><div class="hero-copy"><span class="eyebrow">YOUR CAMPUS. YOUR COMMUNITY.</span><h1>Welcome to<br>CSI AITR.</h1><p>Discover events, register easily, and stay connected. Your next great idea starts here.</p><div class="hero-actions"><a class="button button-primary" href="#events">Explore Events <span aria-hidden="true">→</span></a><a class="text-link" href="#registrations">My registrations ↗</a></div></div><a class="hero-art" href="#event/${featured.id}" aria-label="View Prompt 2 Product event"><div class="hero-art-top"><span class="poster-label">FEATURED EVENT / 01</span><span class="poster-chip">8 OCT 2026</span></div><h2>Prompt<br>2 Product.</h2><div class="poster-bottom"><span>AI & PROMPT ENGINEERING</span><span>VIEW EVENT ↗</span></div></a></div></section><div class="page-wrap"><div class="stats-strip"><div class="stat"><strong>${events.length.toString().padStart(2,'0')}</strong><span>Events to explore</span></div><div class="stat"><strong>${Object.keys(registrations).length.toString().padStart(2,'0')}</strong><span>My registrations</span></div><div class="stat"><strong>${saved.length.toString().padStart(2,'0')}</strong><span>Saved events</span></div></div><div class="section-head"><div><span class="eyebrow">FIND YOUR NEXT THING</span><h2>Upcoming events</h2><p>Learn something new. Meet your people.</p></div><a class="text-link" href="#events">View all events →</a></div><div class="event-grid">${events.filter(e=>!isPast(e)).slice(0,4).map(card).join('')||events.slice(0,4).map(card).join('')}</div></div>`}
function eventsPage(){app.innerHTML=`<div class="page-wrap"><div class="page-intro"><span class="eyebrow">WHAT'S HAPPENING</span><h1 class="page-title">Explore events</h1><p class="page-subtitle">Find the right opportunity to learn, build, and connect.</p></div><div class="filter-bar"><div class="field"><label for="search">Search events</label><div class="search-field"><input id="search" type="search" placeholder="Search by event name" value="${escapeHTML(search)}"></div></div><div class="field"><label for="category">Category</label><select id="category"><option value="">All categories</option>${['AI & Technology','Web Development','Programming','Workshop','Hackathon','Other'].map(c=>`<option value="${c}" ${category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label for="status">Date / status</label><select id="status"><option value="">All events</option><option value="upcoming" ${status==='upcoming'?'selected':''}>Upcoming</option><option value="past" ${status==='past'?'selected':''}>Past</option></select></div></div><div class="result-bar"><span id="result-count"></span><button class="clear-button" id="clear-filters" type="button">Clear filters</button></div><div id="event-results" class="event-grid"></div></div>`;document.querySelector('#search').addEventListener('input',e=>{search=e.target.value;updateResults()});document.querySelector('#category').addEventListener('change',e=>{category=e.target.value;updateResults()});document.querySelector('#status').addEventListener('change',e=>{status=e.target.value;updateResults()});document.querySelector('#clear-filters').addEventListener('click',()=>{search='';category='';status='';document.querySelector('#search').value='';document.querySelector('#category').value='';document.querySelector('#status').value='';updateResults()});updateResults()}
function updateResults(){const filtered=events.filter(e=>e.name.toLowerCase().includes(search.trim().toLowerCase())&&(!category||e.category===category)&&(!status||(status==='past'?isPast(e):!isPast(e))));document.querySelector('#result-count').textContent=`Showing ${filtered.length} of ${events.length} events`;document.querySelector('#event-results').innerHTML=filtered.length?filtered.map(card).join(''):empty('⌕','No events found.','Try a different search or clear the filters.','','')}
function details(e){const registered=Boolean(registrations[e.id]);app.innerHTML=`<div class="page-wrap"><a class="back-link" href="#${previousPage}">← Back to ${previousPage==='home'?'Home':previousPage==='saved'?'Saved Events':previousPage==='registrations'?'My Registrations':'Events'}</a><div class="detail-banner" data-tone="${e.tone}"><span>CSI AITR STUDENT CHAPTER · ${e.category.toUpperCase()}</span><strong>${e.name}</strong><span>${eventDate(e).toUpperCase()} · ${e.venue.toUpperCase()}</span></div><div class="detail-layout"><div class="detail-main"><span class="eyebrow">EVENT DETAILS</span><h1>${e.name}</h1><p class="lead">${e.description}</p><section class="detail-section"><h2>About this event</h2><p>${e.details}</p></section><section class="detail-section"><h2>Event schedule</h2><div class="timeline">${e.schedule.map(([time,label])=>`<div class="timeline-item"><span class="timeline-time">${time}</span><span class="timeline-label">${label}</span></div>`).join('')}</div></section><section class="detail-section"><h2>Event rules</h2><ul>${e.rules.map(rule=>`<li>${rule}</li>`).join('')}</ul></section><section class="detail-section"><h2>Contact & organizer</h2><p>${e.organizer}<br>For questions, contact the CSI AITR Student Chapter at your campus.</p></section></div><aside class="info-panel"><h3>At a glance</h3>${[['▦','Date',eventDate(e)],['◷','Time',e.time],['⌖','Venue',e.venue],['◈','Category',e.category],['♙','Team size',e.team],['₹','Registration fee',e.fee],['✦','Theme',e.theme],['▤','Available seats',String(Math.max(0,e.seats-(registered?1:0)))+' of '+e.seats],['✓','Registration status',registered?'Registered':isPast(e)?'Closed':'Open']].map(([mark,label,value])=>`<div class="info-item"><span class="info-mark">${mark}</span><div><small>${label}</small><strong>${value}</strong></div></div>`).join('')}<div class="panel-actions"><button type="button" class="button button-primary full" data-register="${e.id}" ${isPast(e)?'disabled':''}>${registered?'Registered ✓':isPast(e)?'Registration Closed':'Register Now →'}</button><button type="button" class="button button-outline full" data-save="${e.id}">${saved.includes(e.id)?'♥ Saved Event':'♡ Save Event'}</button><a class="button button-outline full" href="#events">← Back to Events</a></div></aside></div></div>`}
function collection(type){const isSaved=type==='saved',ids=isSaved?saved:Object.keys(registrations),items=events.filter(e=>ids.includes(e.id));app.innerHTML=`<div class="page-wrap"><div class="page-intro"><span class="eyebrow">YOUR CSI AITR</span><h1 class="page-title">${isSaved?'Saved events':'My registrations'}</h1><p class="page-subtitle">${isSaved?'Events you want to keep close.':'All the events you are signed up for.'}</p></div>${items.length?`<div class="list-grid">${items.map(e=>`<article class="list-card"><div><span class="category-pill">${isSaved?e.category:'✓ Registered'}</span><h3>${e.name}</h3><p>▦ ${eventDate(e)} &nbsp; · &nbsp; ⌖ ${e.venue}</p></div><div class="list-actions">${isSaved?`<button class="save-button saved" data-save="${e.id}" type="button" aria-label="Remove saved event: ${e.name}" title="Remove saved event">♥</button>`:''}<a class="button button-outline" href="#event/${e.id}">View Event →</a></div></article>`).join('')}</div>`:empty(isSaved?'♡':'▤',isSaved?'No saved events yet.':'You have not registered for any event yet.',isSaved?'Find an event you like and tap the heart to save it.':'Explore what’s coming up and sign up for something new.','events','Explore events')}</div>`}
function profilePage(){const safe=key=>escapeHTML(profile[key]||'');app.innerHTML=`<div class="page-wrap"><div class="page-intro"><span class="eyebrow">A LITTLE ABOUT YOU</span><h1 class="page-title">My profile</h1><p class="page-subtitle">Keep your details up to date for event registrations.</p></div><div class="profile-panel"><div class="profile-heading"><span class="profile-avatar">${safe('name').trim().charAt(0).toUpperCase()||'S'}</span><div><h2>${safe('name')}</h2><p>${safe('email')}</p></div></div>${editing?`<form id="profile-form" class="profile-form"><label>Student name<input name="name" required value="${safe('name')}"></label><label>Email<input name="email" type="email" required value="${safe('email')}"></label><label>College<input name="college" required value="${safe('college')}"></label><label>Branch<input name="branch" required value="${safe('branch')}"></label><div class="profile-form-actions"><button class="button button-primary" type="submit">Save Profile</button><button class="button button-outline" type="button" id="cancel-profile">Cancel</button></div></form>`:`<div class="profile-info"><div><small>STUDENT NAME</small><strong>${safe('name')}</strong></div><div><small>EMAIL ADDRESS</small><strong>${safe('email')}</strong></div><div><small>COLLEGE</small><strong>${safe('college')}</strong></div><div><small>BRANCH</small><strong>${safe('branch')}</strong></div></div><div><button class="button button-outline" id="edit-profile" type="button">Edit Profile →</button></div>`}</div></div>`;if(editing){document.querySelector('#profile-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);profile=Object.fromEntries(['name','email','college','branch'].map(key=>[key,String(data.get(key)||'').trim()]));store('profile',profile);editing=false;profilePage();nav();notify('Profile updated successfully.')});document.querySelector('#cancel-profile').addEventListener('click',()=>{editing=false;profilePage()})}else document.querySelector('#edit-profile').addEventListener('click',()=>{editing=true;profilePage()})}
function render(){const hash=decodeURIComponent(location.hash.slice(1)||'home'),[page,id]=hash.split('/');if(page==='event'&&events.some(e=>e.id===id)){details(events.find(e=>e.id===id))}else if(page==='events')eventsPage();else if(page==='saved')collection('saved');else if(page==='registrations')collection('registrations');else if(page==='profile')profilePage();else home();nav();window.scrollTo(0,0)}
// Preserve the section a details link was opened from for the back link.
document.addEventListener('click',e=>{const link=e.target.closest('a[href^="#event/"]');if(link){previousPage=location.hash.slice(1).split('/')[0]||'home'}const save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;if(saved.includes(id)){saved=saved.filter(item=>item!==id);notify('Event removed from saved events.')}else{saved.push(id);notify('Event saved.')}store('saved',saved);const focusId=id;render();const newButton=document.querySelector(`[data-save="${focusId}"]`);newButton?.focus()}const register=e.target.closest('[data-register]');if(register){const id=register.dataset.register;if(registrations[id]){notify('You are already registered for this event.');return}const event=events.find(item=>item.id===id);if(!event||isPast(event))return;activeEvent=id;form.reset();document.querySelector('#form-error').hidden=true;document.querySelector('#register-event-name').textContent=event.name+' · '+eventDate(event);form.elements.name.value=profile.name==='Student Name'?'':profile.name;form.elements.email.value=profile.email==='student@aitr.ac.in'?'':profile.email;form.elements.college.value=profile.college==='Acropolis Institute of Technology & Research'?'':profile.college;dialog.showModal()}});
form.addEventListener('submit',e=>{e.preventDefault();if(!activeEvent)return;if(registrations[activeEvent]){dialog.close();notify('You are already registered for this event.');return}const data=new FormData(form),entry=Object.fromEntries(['name','email','phone','college'].map(key=>[key,String(data.get(key)||'').trim()]));const error=document.querySelector('#form-error');if(Object.values(entry).some(value=>!value)){error.textContent='Please complete all fields.';error.hidden=false;return}if(!/^[0-9+() -]{10,16}$/.test(entry.phone)){error.textContent='Please enter a valid phone number.';error.hidden=false;return}registrations[activeEvent]={...entry,registeredAt:new Date().toISOString()};store('registrations',registrations);dialog.close();render();notify('Registration successful! Find your event in My Registrations.')});
document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});window.addEventListener('hashchange',render);render();
